import { indexById } from "./helpers";
import type {
  AgentWorker,
  Artifact,
  Invoice,
  PaymentIntent,
  PurchaseOrder,
  Vendor,
} from "./types";

export const workerFixtures = [
  {
    id: "worker-intake",
    name: "Intake Worker",
    role: "Document intake and case assembly",
    team: "FinOps Control",
    summary:
      "Normalizes inbound packets, checks submission completeness, and opens the first supervised workflow lane.",
    supervisionModel: "shadow-first",
    defaultQueue: "Inbound invoice packets",
    specialties: ["packet assembly", "artifact triage", "submission provenance"],
    handoffTargets: ["worker-vendor-review", "worker-po-match"],
  },
  {
    id: "worker-vendor-review",
    name: "Vendor Review Worker",
    role: "Vendor identity and remittance validation",
    team: "FinOps Control",
    summary:
      "Resolves vendor identity, checks master-data drift, and isolates remittance changes before any payment release can advance.",
    supervisionModel: "approval-gated",
    defaultQueue: "Vendor verification",
    specialties: ["vendor resolution", "bank account change review", "master-data evidence"],
    handoffTargets: ["worker-risk", "worker-approval-coordinator"],
  },
  {
    id: "worker-po-match",
    name: "PO Match Worker",
    role: "Three-way match and invoice variance review",
    team: "FinOps Control",
    summary:
      "Compares invoice packets against purchase orders and supporting proof so amount and quantity drift stay visible.",
    supervisionModel: "shadow-first",
    defaultQueue: "PO-backed invoices",
    specialties: ["three-way match", "line-item variance", "receiving evidence"],
    handoffTargets: ["worker-risk", "worker-execution"],
  },
  {
    id: "worker-risk",
    name: "Risk Worker",
    role: "Risk posture and exception framing",
    team: "Control Plane",
    summary:
      "Turns suspicious patterns into concrete review context, naming the evidence bundle and containment action needed next.",
    supervisionModel: "approval-gated",
    defaultQueue: "Escalated exceptions",
    specialties: ["risk notes", "control posture", "exception summarization"],
    handoffTargets: ["worker-approval-coordinator", "worker-execution"],
  },
  {
    id: "worker-approval-coordinator",
    name: "Approval Coordinator",
    role: "Human review routing and release control",
    team: "Control Plane",
    summary:
      "Packages the exact action waiting on approval, assigns the named reviewer, and records the safe resume path.",
    supervisionModel: "approval-gated",
    defaultQueue: "Pending approvals",
    specialties: ["approval packet assembly", "review routing", "release holds"],
    handoffTargets: ["worker-execution", "worker-risk"],
  },
  {
    id: "worker-execution",
    name: "Execution Worker",
    role: "Controlled posting and payment execution",
    team: "FinOps Operations",
    summary:
      "Advances only after the evidence set is complete, approvals are satisfied, and the release path is explicitly cleared.",
    supervisionModel: "controlled-execution",
    defaultQueue: "Ready-for-release actions",
    specialties: ["erp posting", "payment release", "execution receipts"],
    handoffTargets: ["worker-risk"],
  },
] satisfies AgentWorker[];

export const artifactFixtures = [
  {
    id: "artifact-vendor-brightpath-master-snapshot",
    kind: "vendor_master_snapshot",
    title: "BrightPath vendor master snapshot",
    fileName: "brightpath-vendor-master-2026-03-15.pdf",
    status: "available",
    sourceSystem: "ERP Vendor Master",
    capturedAt: "2026-03-15T10:20:00Z",
    relatedEntityIds: ["vendor-brightpath-studio"],
    summary: "Approved creative-services vendor profile with stable ACH instructions and current tax documentation.",
  },
  {
    id: "artifact-vendor-ridgeway-master-snapshot",
    kind: "vendor_master_snapshot",
    title: "Ridgeway vendor master snapshot",
    fileName: "ridgeway-vendor-master-2026-02-28.pdf",
    status: "available",
    sourceSystem: "ERP Vendor Master",
    capturedAt: "2026-02-28T09:05:00Z",
    relatedEntityIds: ["vendor-ridgeway-industrial"],
    summary: "Established industrial supply vendor with approved receiving workflow and tolerance notes.",
  },
  {
    id: "artifact-vendor-aperture-master-snapshot",
    kind: "vendor_master_snapshot",
    title: "Aperture vendor master snapshot",
    fileName: "aperture-vendor-master-2026-03-20.pdf",
    status: "available",
    sourceSystem: "ERP Vendor Master",
    capturedAt: "2026-03-20T12:30:00Z",
    relatedEntityIds: ["vendor-aperture-logistics"],
    summary: "Freight vendor profile captured before a recent remittance account update request entered review.",
  },
  {
    id: "artifact-vendor-bluefield-master-snapshot",
    kind: "vendor_master_snapshot",
    title: "Bluefield vendor master snapshot",
    fileName: "bluefield-vendor-master-2026-01-18.pdf",
    status: "available",
    sourceSystem: "ERP Vendor Master",
    capturedAt: "2026-01-18T14:10:00Z",
    relatedEntityIds: ["vendor-bluefield-field-services"],
    summary: "Active field-services vendor profile that still requires current tax paperwork before release.",
  },
  {
    id: "artifact-vendor-cinder-master-snapshot",
    kind: "vendor_master_snapshot",
    title: "Cinder Cloud vendor master snapshot",
    fileName: "cinder-cloud-vendor-master-2026-03-01.pdf",
    status: "available",
    sourceSystem: "ERP Vendor Master",
    capturedAt: "2026-03-01T08:45:00Z",
    relatedEntityIds: ["vendor-cinder-cloud"],
    summary: "Strategic cloud vendor with stable wire instructions and quarterly spend review controls.",
  },
  {
    id: "artifact-invoice-brightpath-2048-pdf",
    kind: "invoice_pdf",
    title: "Invoice BP-2048",
    fileName: "BP-2048.pdf",
    status: "available",
    sourceSystem: "Vendor Portal",
    capturedAt: "2026-03-12T15:02:00Z",
    relatedEntityIds: ["invoice-brightpath-2048", "vendor-brightpath-studio"],
    summary: "March creative retainer invoice submitted with matching PO reference and media deliverable schedule.",
  },
  {
    id: "artifact-po-24017-pdf",
    kind: "purchase_order_pdf",
    title: "PO-24017 approved purchase order",
    fileName: "PO-24017.pdf",
    status: "available",
    sourceSystem: "ERP Purchasing",
    capturedAt: "2026-02-25T11:40:00Z",
    relatedEntityIds: ["po-brightpath-24017", "vendor-brightpath-studio"],
    summary: "Approved Q2 creative services PO for Helios Retail Group digital acquisition campaigns.",
  },
  {
    id: "artifact-sow-brightpath-q2-retainer",
    kind: "statement_of_work",
    title: "BrightPath Q2 creative retainer SOW",
    fileName: "brightpath-q2-sow.pdf",
    status: "available",
    sourceSystem: "Contract Repository",
    capturedAt: "2026-02-24T17:15:00Z",
    relatedEntityIds: ["invoice-brightpath-2048", "po-brightpath-24017"],
    summary: "Signed statement of work covering campaign asset production, revisions, and monthly billing cadence.",
  },
  {
    id: "artifact-invoice-pinecrest-8831-pdf",
    kind: "invoice_pdf",
    title: "Invoice PC-8831",
    fileName: "PC-8831.pdf",
    status: "available",
    sourceSystem: "Shared Mailbox",
    capturedAt: "2026-03-18T09:18:00Z",
    relatedEntityIds: ["invoice-pinecrest-8831"],
    summary: "Consulting invoice received by email with no matching vendor master record or PO reference.",
  },
  {
    id: "artifact-email-pinecrest-introduction",
    kind: "email_thread",
    title: "Pinecrest introduction email thread",
    fileName: "pinecrest-introduction.eml",
    status: "available",
    sourceSystem: "Email Archive",
    capturedAt: "2026-03-18T09:20:00Z",
    relatedEntityIds: ["invoice-pinecrest-8831"],
    summary: "Forwarded email claims executive sponsorship for a process-mapping engagement but lacks procurement approval.",
  },
  {
    id: "artifact-intake-note-pinecrest-unresolved",
    kind: "intake_note",
    title: "Unresolved vendor intake note",
    fileName: "pinecrest-unresolved-note.txt",
    status: "flagged",
    sourceSystem: "Aegis Intake",
    capturedAt: "2026-03-18T09:31:00Z",
    relatedEntityIds: ["invoice-pinecrest-8831"],
    summary: "Intake worker could not map Pinecrest Advisory LLC to an active vendor record or approved onboarding request.",
  },
  {
    id: "artifact-invoice-ridgeway-7710-pdf",
    kind: "invoice_pdf",
    title: "Invoice RW-7710",
    fileName: "RW-7710.pdf",
    status: "available",
    sourceSystem: "Vendor Portal",
    capturedAt: "2026-03-21T13:12:00Z",
    relatedEntityIds: ["invoice-ridgeway-7710", "vendor-ridgeway-industrial"],
    summary: "Industrial parts invoice references PO-24054 but carries an amount above the approved purchase order value.",
  },
  {
    id: "artifact-po-24054-pdf",
    kind: "purchase_order_pdf",
    title: "PO-24054 approved purchase order",
    fileName: "PO-24054.pdf",
    status: "available",
    sourceSystem: "ERP Purchasing",
    capturedAt: "2026-03-02T10:22:00Z",
    relatedEntityIds: ["po-ridgeway-24054", "vendor-ridgeway-industrial"],
    summary: "Approved replacement-parts order with fixed quantity and freight terms for a scheduled warehouse retrofit.",
  },
  {
    id: "artifact-receiving-ridgeway-batch-17",
    kind: "goods_receipt",
    title: "Receiving log batch 17",
    fileName: "ridgeway-batch-17.csv",
    status: "available",
    sourceSystem: "Warehouse Ops",
    capturedAt: "2026-03-20T18:05:00Z",
    relatedEntityIds: ["invoice-ridgeway-7710", "po-ridgeway-24054"],
    summary: "Receiving log confirms only the original PO quantity landed, leaving the invoice overbilled against received goods.",
  },
  {
    id: "artifact-invoice-aperture-1127-pdf",
    kind: "invoice_pdf",
    title: "Invoice AP-1127",
    fileName: "AP-1127.pdf",
    status: "available",
    sourceSystem: "EDI Gateway",
    capturedAt: "2026-03-26T07:55:00Z",
    relatedEntityIds: ["invoice-aperture-1127", "vendor-aperture-logistics"],
    summary: "Freight services invoice submitted after monthly lane reconciliation and before remittance release.",
  },
  {
    id: "artifact-po-24061-pdf",
    kind: "purchase_order_pdf",
    title: "PO-24061 approved purchase order",
    fileName: "PO-24061.pdf",
    status: "available",
    sourceSystem: "ERP Purchasing",
    capturedAt: "2026-03-08T16:44:00Z",
    relatedEntityIds: ["po-aperture-24061", "vendor-aperture-logistics"],
    summary: "Approved freight services PO with expected March lane allocation and approved fuel surcharge range.",
  },
  {
    id: "artifact-bank-change-aperture-mar-26",
    kind: "bank_change_request",
    title: "Aperture bank change request",
    fileName: "aperture-bank-change-mar-26.pdf",
    status: "flagged",
    sourceSystem: "Vendor Portal",
    capturedAt: "2026-03-26T08:11:00Z",
    relatedEntityIds: ["vendor-aperture-logistics", "payment-intent-aperture-1127"],
    summary: "Vendor submitted a new primary bank account three days before scheduled payment release.",
  },
  {
    id: "artifact-remittance-comparison-aperture",
    kind: "remittance_comparison",
    title: "Aperture remittance profile comparison",
    fileName: "aperture-remittance-drift.xlsx",
    status: "flagged",
    sourceSystem: "Aegis Risk",
    capturedAt: "2026-03-27T10:04:00Z",
    relatedEntityIds: ["vendor-aperture-logistics", "payment-intent-aperture-1127"],
    summary: "Comparison highlights a new receiving bank and beneficiary address drift from prior settled batches.",
  },
  {
    id: "artifact-invoice-bluefield-9044-pdf",
    kind: "invoice_pdf",
    title: "Invoice BF-9044",
    fileName: "BF-9044.pdf",
    status: "available",
    sourceSystem: "Shared Mailbox",
    capturedAt: "2026-03-11T11:16:00Z",
    relatedEntityIds: ["invoice-bluefield-9044", "vendor-bluefield-field-services"],
    summary: "Facilities maintenance invoice references an approved PO but the compliance packet is incomplete.",
  },
  {
    id: "artifact-po-24072-pdf",
    kind: "purchase_order_pdf",
    title: "PO-24072 approved purchase order",
    fileName: "PO-24072.pdf",
    status: "available",
    sourceSystem: "ERP Purchasing",
    capturedAt: "2026-02-27T14:38:00Z",
    relatedEntityIds: ["po-bluefield-24072", "vendor-bluefield-field-services"],
    summary: "Approved store-maintenance PO with recurring site visit schedule and fixed travel allowance.",
  },
  {
    id: "artifact-w9-bluefield-2026",
    kind: "tax_document",
    title: "Bluefield W-9 renewal",
    status: "missing",
    sourceSystem: "Vendor Compliance",
    capturedAt: "2026-03-11T11:22:00Z",
    relatedEntityIds: ["vendor-bluefield-field-services", "invoice-bluefield-9044"],
    summary: "Current-year tax form is still missing, preventing the packet from clearing compliance release.",
  },
  {
    id: "artifact-site-completion-note-hel-118",
    kind: "completion_note",
    title: "Store 118 completion note",
    fileName: "hel-store-118-completion-note.pdf",
    status: "available",
    sourceSystem: "Field Ops",
    capturedAt: "2026-03-10T19:40:00Z",
    relatedEntityIds: ["invoice-bluefield-9044", "po-bluefield-24072"],
    summary: "Site completion note confirms the maintenance work occurred even though compliance docs remain incomplete.",
  },
  {
    id: "artifact-invoice-cinder-3308-pdf",
    kind: "invoice_pdf",
    title: "Invoice CC-3308",
    fileName: "CC-3308.pdf",
    status: "available",
    sourceSystem: "Vendor Portal",
    capturedAt: "2026-03-22T06:50:00Z",
    relatedEntityIds: ["invoice-cinder-3308", "vendor-cinder-cloud"],
    summary: "Quarterly cloud platform invoice aligns to committed services but exceeds the autonomous payment threshold.",
  },
  {
    id: "artifact-po-24088-pdf",
    kind: "purchase_order_pdf",
    title: "PO-24088 approved purchase order",
    fileName: "PO-24088.pdf",
    status: "available",
    sourceSystem: "ERP Purchasing",
    capturedAt: "2026-03-03T09:26:00Z",
    relatedEntityIds: ["po-cinder-24088", "vendor-cinder-cloud"],
    summary: "Approved annual cloud capacity order with executive budget signoff and spend ceiling references.",
  },
  {
    id: "artifact-consumption-report-cinder-feb",
    kind: "consumption_report",
    title: "February cloud consumption report",
    fileName: "cinder-feb-consumption.csv",
    status: "available",
    sourceSystem: "Cloud Billing",
    capturedAt: "2026-03-21T23:55:00Z",
    relatedEntityIds: ["invoice-cinder-3308", "po-cinder-24088"],
    summary: "Usage report supports the billed capacity, leaving approval threshold as the only gating concern.",
  },
  {
    id: "artifact-msa-cinder-cloud",
    kind: "master_services_agreement",
    title: "Cinder Cloud MSA",
    fileName: "cinder-cloud-msa.pdf",
    status: "available",
    sourceSystem: "Contract Repository",
    capturedAt: "2025-12-15T15:30:00Z",
    relatedEntityIds: ["vendor-cinder-cloud", "po-cinder-24088"],
    summary: "Master services agreement captures wire payment terms, annual commit structure, and approval responsibilities.",
  },
] satisfies Artifact[];

export const vendorFixtures = [
  {
    id: "vendor-brightpath-studio",
    vendorCode: "V-1048",
    name: "BrightPath Studio",
    legalName: "BrightPath Creative Studio LLC",
    category: "Creative services",
    operatingRegion: "North America",
    owner: "Marketing Procurement",
    trustTier: "trusted",
    onboardingStatus: "active",
    paymentTerms: "Net 30",
    currency: "USD",
    lastReviewedAt: "2026-03-15",
    bankAccounts: [
      {
        id: "bank-brightpath-primary",
        bankName: "First Republic Commerce",
        maskedAccountNumber: "....0482",
        routingLast4: "2201",
        country: "US",
        currency: "USD",
        isPrimary: true,
        lastChangedAt: "2025-11-08",
        changeSource: "annual review",
      },
    ],
    artifactIds: ["artifact-vendor-brightpath-master-snapshot"],
    notes: [
      "Used for monthly campaign production retainers.",
      "No unresolved exceptions in the last four billing cycles.",
    ],
  },
  {
    id: "vendor-ridgeway-industrial",
    vendorCode: "V-2094",
    name: "Ridgeway Industrial Supply",
    legalName: "Ridgeway Industrial Supply Co.",
    category: "Industrial parts",
    operatingRegion: "Midwest US",
    owner: "Warehouse Procurement",
    trustTier: "trusted",
    onboardingStatus: "active",
    paymentTerms: "Net 45",
    currency: "USD",
    lastReviewedAt: "2026-02-28",
    bankAccounts: [
      {
        id: "bank-ridgeway-primary",
        bankName: "Lakeview Business Bank",
        maskedAccountNumber: "....7719",
        routingLast4: "0041",
        country: "US",
        currency: "USD",
        isPrimary: true,
        lastChangedAt: "2025-08-14",
        changeSource: "vendor onboarding",
      },
    ],
    artifactIds: ["artifact-vendor-ridgeway-master-snapshot"],
    notes: [
      "Receiving confirmation is required for mechanical replacement orders.",
      "Prior exceptions have been quantity-related, not remittance-related.",
    ],
  },
  {
    id: "vendor-aperture-logistics",
    vendorCode: "V-3182",
    name: "Aperture Logistics",
    legalName: "Aperture Logistics Network Inc.",
    category: "Freight services",
    operatingRegion: "North America",
    owner: "Transportation Finance",
    trustTier: "monitored",
    onboardingStatus: "active",
    paymentTerms: "Net 21",
    currency: "USD",
    lastReviewedAt: "2026-03-20",
    bankAccounts: [
      {
        id: "bank-aperture-legacy",
        bankName: "Union Freight Bank",
        maskedAccountNumber: "....2084",
        routingLast4: "1180",
        country: "US",
        currency: "USD",
        isPrimary: false,
        lastChangedAt: "2024-09-30",
        changeSource: "annual review",
      },
      {
        id: "bank-aperture-new",
        bankName: "Meridian Treasury Bank",
        maskedAccountNumber: "....5517",
        routingLast4: "9032",
        country: "US",
        currency: "USD",
        isPrimary: true,
        lastChangedAt: "2026-03-26",
        changeSource: "vendor-initiated bank update",
      },
    ],
    artifactIds: [
      "artifact-vendor-aperture-master-snapshot",
      "artifact-bank-change-aperture-mar-26",
      "artifact-remittance-comparison-aperture",
    ],
    notes: [
      "Primary bank account changed within the current billing cycle.",
      "Any release over a new account requires finance review.",
    ],
  },
  {
    id: "vendor-bluefield-field-services",
    vendorCode: "V-2270",
    name: "Bluefield Field Services",
    legalName: "Bluefield Field Services LLC",
    category: "Facilities maintenance",
    operatingRegion: "Southwest US",
    owner: "Facilities Procurement",
    trustTier: "monitored",
    onboardingStatus: "active",
    paymentTerms: "Net 30",
    currency: "USD",
    lastReviewedAt: "2026-01-18",
    bankAccounts: [
      {
        id: "bank-bluefield-primary",
        bankName: "Summit Commercial Bank",
        maskedAccountNumber: "....6640",
        routingLast4: "5529",
        country: "US",
        currency: "USD",
        isPrimary: true,
        lastChangedAt: "2025-04-11",
        changeSource: "vendor onboarding",
      },
    ],
    artifactIds: [
      "artifact-vendor-bluefield-master-snapshot",
      "artifact-w9-bluefield-2026",
    ],
    notes: [
      "Current tax document renewal is outstanding.",
      "Field work is complete but compliance clearance is not.",
    ],
  },
  {
    id: "vendor-cinder-cloud",
    vendorCode: "V-4116",
    name: "Cinder Cloud",
    legalName: "Cinder Cloud Platforms, Inc.",
    category: "Cloud infrastructure",
    operatingRegion: "Global",
    owner: "Technology Procurement",
    trustTier: "trusted",
    onboardingStatus: "active",
    paymentTerms: "Net 15",
    currency: "USD",
    lastReviewedAt: "2026-03-01",
    bankAccounts: [
      {
        id: "bank-cinder-primary",
        bankName: "National Treasury Bank",
        maskedAccountNumber: "....8702",
        routingLast4: "6207",
        country: "US",
        currency: "USD",
        isPrimary: true,
        lastChangedAt: "2025-06-19",
        changeSource: "annual compliance renewal",
      },
    ],
    artifactIds: [
      "artifact-vendor-cinder-master-snapshot",
      "artifact-msa-cinder-cloud",
    ],
    notes: [
      "Quarterly cloud bills are approved when matched but still route through spend threshold control.",
      "Executive budget owner signs off on releases over 150000 USD.",
    ],
  },
] satisfies Vendor[];

export const purchaseOrderFixtures = [
  {
    id: "po-brightpath-24017",
    poNumber: "PO-24017",
    operatingEntity: "Helios Retail Group",
    vendorId: "vendor-brightpath-studio",
    requester: "Maya Chen",
    department: "Growth Marketing",
    issuedAt: "2026-02-25",
    currency: "USD",
    subtotalAmount: 17000,
    taxAmount: 1420,
    totalAmount: 18420,
    remainingAmount: 0,
    status: "matched",
    lineItems: [
      {
        id: "po-line-brightpath-1",
        description: "March campaign creative retainer",
        quantity: 1,
        unitPrice: 17000,
        amount: 17000,
        department: "Growth Marketing",
      },
    ],
    artifactIds: ["artifact-po-24017-pdf", "artifact-sow-brightpath-q2-retainer"],
  },
  {
    id: "po-ridgeway-24054",
    poNumber: "PO-24054",
    operatingEntity: "Northwind Distribution",
    vendorId: "vendor-ridgeway-industrial",
    requester: "Elena Ruiz",
    department: "Warehouse Operations",
    issuedAt: "2026-03-02",
    currency: "USD",
    subtotalAmount: 85000,
    taxAmount: 7450,
    totalAmount: 92450,
    remainingAmount: 0,
    status: "disputed",
    lineItems: [
      {
        id: "po-line-ridgeway-1",
        description: "Conveyor motor assemblies",
        quantity: 25,
        unitPrice: 2800,
        amount: 70000,
        department: "Warehouse Operations",
      },
      {
        id: "po-line-ridgeway-2",
        description: "Installation hardware kits",
        quantity: 25,
        unitPrice: 600,
        amount: 15000,
        department: "Warehouse Operations",
      },
    ],
    artifactIds: ["artifact-po-24054-pdf", "artifact-receiving-ridgeway-batch-17"],
  },
  {
    id: "po-aperture-24061",
    poNumber: "PO-24061",
    operatingEntity: "Beacon Freight Services",
    vendorId: "vendor-aperture-logistics",
    requester: "Marcus Hale",
    department: "Transportation Finance",
    issuedAt: "2026-03-08",
    currency: "USD",
    subtotalAmount: 45000,
    taxAmount: 3300,
    totalAmount: 48300,
    remainingAmount: 0,
    status: "matched",
    lineItems: [
      {
        id: "po-line-aperture-1",
        description: "Regional freight lane management",
        quantity: 1,
        unitPrice: 45000,
        amount: 45000,
        department: "Transportation Finance",
      },
    ],
    artifactIds: ["artifact-po-24061-pdf"],
  },
  {
    id: "po-bluefield-24072",
    poNumber: "PO-24072",
    operatingEntity: "Helios Retail Group",
    vendorId: "vendor-bluefield-field-services",
    requester: "Jonah Brooks",
    department: "Store Operations",
    issuedAt: "2026-02-27",
    currency: "USD",
    subtotalAmount: 20400,
    taxAmount: 1740,
    totalAmount: 22140,
    remainingAmount: 0,
    status: "matched",
    lineItems: [
      {
        id: "po-line-bluefield-1",
        description: "Store 118 HVAC maintenance and filter replacement",
        quantity: 1,
        unitPrice: 20400,
        amount: 20400,
        department: "Store Operations",
      },
    ],
    artifactIds: ["artifact-po-24072-pdf", "artifact-site-completion-note-hel-118"],
  },
  {
    id: "po-cinder-24088",
    poNumber: "PO-24088",
    operatingEntity: "Northwind Distribution",
    vendorId: "vendor-cinder-cloud",
    requester: "Priya Shah",
    department: "Infrastructure Engineering",
    issuedAt: "2026-03-03",
    currency: "USD",
    subtotalAmount: 150000,
    taxAmount: 12480,
    totalAmount: 162480,
    remainingAmount: 0,
    status: "matched",
    lineItems: [
      {
        id: "po-line-cinder-1",
        description: "Quarterly reserved cloud capacity",
        quantity: 1,
        unitPrice: 150000,
        amount: 150000,
        department: "Infrastructure Engineering",
      },
    ],
    artifactIds: [
      "artifact-po-24088-pdf",
      "artifact-consumption-report-cinder-feb",
      "artifact-msa-cinder-cloud",
    ],
  },
] satisfies PurchaseOrder[];

export const invoiceFixtures = [
  {
    id: "invoice-brightpath-2048",
    invoiceNumber: "BP-2048",
    operatingEntity: "Helios Retail Group",
    businessUnit: "Growth Marketing",
    vendorId: "vendor-brightpath-studio",
    submittedVendorName: "BrightPath Studio",
    submittedRemittanceEmail: "billing@brightpathstudio.com",
    issueDate: "2026-03-10",
    receivedAt: "2026-03-12T15:02:00Z",
    dueDate: "2026-04-09",
    currency: "USD",
    subtotalAmount: 17000,
    taxAmount: 1420,
    totalAmount: 18420,
    paymentTerms: "Net 30",
    purchaseOrderId: "po-brightpath-24017",
    lineItems: [
      {
        id: "invoice-line-brightpath-1",
        description: "March campaign creative retainer",
        quantity: 1,
        unitPrice: 17000,
        amount: 17000,
        costCenter: "MKT-440",
      },
    ],
    artifactIds: [
      "artifact-invoice-brightpath-2048-pdf",
      "artifact-po-24017-pdf",
      "artifact-sow-brightpath-q2-retainer",
    ],
    status: "ready_for_payment",
  },
  {
    id: "invoice-pinecrest-8831",
    invoiceNumber: "PC-8831",
    operatingEntity: "Northwind Distribution",
    businessUnit: "Finance Transformation",
    submittedVendorName: "Pinecrest Advisory LLC",
    submittedRemittanceEmail: "accounts@pinecrestadvisory.co",
    issueDate: "2026-03-16",
    receivedAt: "2026-03-18T09:18:00Z",
    dueDate: "2026-04-15",
    currency: "USD",
    subtotalAmount: 25750,
    taxAmount: 2100,
    totalAmount: 27850,
    paymentTerms: "Net 30",
    lineItems: [
      {
        id: "invoice-line-pinecrest-1",
        description: "Process mapping workshop and findings memo",
        quantity: 1,
        unitPrice: 25750,
        amount: 25750,
        costCenter: "FIN-218",
      },
    ],
    artifactIds: [
      "artifact-invoice-pinecrest-8831-pdf",
      "artifact-email-pinecrest-introduction",
      "artifact-intake-note-pinecrest-unresolved",
    ],
    status: "exception",
  },
  {
    id: "invoice-ridgeway-7710",
    invoiceNumber: "RW-7710",
    operatingEntity: "Northwind Distribution",
    businessUnit: "Warehouse Operations",
    vendorId: "vendor-ridgeway-industrial",
    submittedVendorName: "Ridgeway Industrial Supply",
    submittedRemittanceEmail: "ap@ridgewayindustrial.com",
    issueDate: "2026-03-20",
    receivedAt: "2026-03-21T13:12:00Z",
    dueDate: "2026-05-05",
    currency: "USD",
    subtotalAmount: 91800,
    taxAmount: 7860,
    totalAmount: 99660,
    paymentTerms: "Net 45",
    purchaseOrderId: "po-ridgeway-24054",
    lineItems: [
      {
        id: "invoice-line-ridgeway-1",
        description: "Conveyor motor assemblies",
        quantity: 27,
        unitPrice: 2800,
        amount: 75600,
        costCenter: "OPS-302",
      },
      {
        id: "invoice-line-ridgeway-2",
        description: "Installation hardware kits",
        quantity: 27,
        unitPrice: 600,
        amount: 16200,
        costCenter: "OPS-302",
      },
    ],
    artifactIds: [
      "artifact-invoice-ridgeway-7710-pdf",
      "artifact-po-24054-pdf",
      "artifact-receiving-ridgeway-batch-17",
    ],
    status: "exception",
  },
  {
    id: "invoice-aperture-1127",
    invoiceNumber: "AP-1127",
    operatingEntity: "Beacon Freight Services",
    businessUnit: "Transportation Finance",
    vendorId: "vendor-aperture-logistics",
    submittedVendorName: "Aperture Logistics",
    submittedRemittanceEmail: "settlements@aperturelogistics.com",
    issueDate: "2026-03-24",
    receivedAt: "2026-03-26T07:55:00Z",
    dueDate: "2026-04-16",
    currency: "USD",
    subtotalAmount: 45000,
    taxAmount: 3300,
    totalAmount: 48300,
    paymentTerms: "Net 21",
    purchaseOrderId: "po-aperture-24061",
    lineItems: [
      {
        id: "invoice-line-aperture-1",
        description: "March regional freight lane settlement",
        quantity: 1,
        unitPrice: 45000,
        amount: 45000,
        costCenter: "LOG-180",
      },
    ],
    artifactIds: [
      "artifact-invoice-aperture-1127-pdf",
      "artifact-po-24061-pdf",
      "artifact-bank-change-aperture-mar-26",
      "artifact-remittance-comparison-aperture",
    ],
    status: "exception",
  },
  {
    id: "invoice-bluefield-9044",
    invoiceNumber: "BF-9044",
    operatingEntity: "Helios Retail Group",
    businessUnit: "Store Operations",
    vendorId: "vendor-bluefield-field-services",
    submittedVendorName: "Bluefield Field Services",
    submittedRemittanceEmail: "billing@bluefieldfs.com",
    issueDate: "2026-03-09",
    receivedAt: "2026-03-11T11:16:00Z",
    dueDate: "2026-04-10",
    currency: "USD",
    subtotalAmount: 20400,
    taxAmount: 1740,
    totalAmount: 22140,
    paymentTerms: "Net 30",
    purchaseOrderId: "po-bluefield-24072",
    lineItems: [
      {
        id: "invoice-line-bluefield-1",
        description: "Store 118 HVAC maintenance and filter replacement",
        quantity: 1,
        unitPrice: 20400,
        amount: 20400,
        costCenter: "OPS-118",
      },
    ],
    artifactIds: [
      "artifact-invoice-bluefield-9044-pdf",
      "artifact-po-24072-pdf",
      "artifact-site-completion-note-hel-118",
      "artifact-w9-bluefield-2026",
    ],
    status: "blocked",
  },
  {
    id: "invoice-cinder-3308",
    invoiceNumber: "CC-3308",
    operatingEntity: "Northwind Distribution",
    businessUnit: "Infrastructure Engineering",
    vendorId: "vendor-cinder-cloud",
    submittedVendorName: "Cinder Cloud",
    submittedRemittanceEmail: "billing@cindercloud.com",
    issueDate: "2026-03-20",
    receivedAt: "2026-03-22T06:50:00Z",
    dueDate: "2026-04-06",
    currency: "USD",
    subtotalAmount: 150000,
    taxAmount: 12480,
    totalAmount: 162480,
    paymentTerms: "Net 15",
    purchaseOrderId: "po-cinder-24088",
    lineItems: [
      {
        id: "invoice-line-cinder-1",
        description: "Quarterly reserved cloud capacity",
        quantity: 1,
        unitPrice: 150000,
        amount: 150000,
        costCenter: "TECH-622",
      },
    ],
    artifactIds: [
      "artifact-invoice-cinder-3308-pdf",
      "artifact-po-24088-pdf",
      "artifact-consumption-report-cinder-feb",
      "artifact-msa-cinder-cloud",
    ],
    status: "matched",
  },
] satisfies Invoice[];

export const paymentIntentFixtures = [
  {
    id: "payment-intent-brightpath-2048",
    invoiceId: "invoice-brightpath-2048",
    vendorId: "vendor-brightpath-studio",
    operatingEntity: "Helios Retail Group",
    amount: 18420,
    currency: "USD",
    paymentMethod: "ach",
    destinationBankAccountId: "bank-brightpath-primary",
    scheduledExecutionDate: "2026-04-02",
    status: "ready",
    approvalThresholdAmount: 50000,
    artifactIds: ["artifact-invoice-brightpath-2048-pdf", "artifact-vendor-brightpath-master-snapshot"],
  },
  {
    id: "payment-intent-ridgeway-7710",
    invoiceId: "invoice-ridgeway-7710",
    vendorId: "vendor-ridgeway-industrial",
    operatingEntity: "Northwind Distribution",
    amount: 99660,
    currency: "USD",
    paymentMethod: "ach",
    destinationBankAccountId: "bank-ridgeway-primary",
    scheduledExecutionDate: "2026-04-18",
    status: "on_hold",
    approvalThresholdAmount: 100000,
    artifactIds: [
      "artifact-invoice-ridgeway-7710-pdf",
      "artifact-po-24054-pdf",
      "artifact-receiving-ridgeway-batch-17",
    ],
  },
  {
    id: "payment-intent-aperture-1127",
    invoiceId: "invoice-aperture-1127",
    vendorId: "vendor-aperture-logistics",
    operatingEntity: "Beacon Freight Services",
    amount: 48300,
    currency: "USD",
    paymentMethod: "ach",
    destinationBankAccountId: "bank-aperture-new",
    scheduledExecutionDate: "2026-03-29",
    status: "on_hold",
    approvalThresholdAmount: 40000,
    artifactIds: [
      "artifact-invoice-aperture-1127-pdf",
      "artifact-bank-change-aperture-mar-26",
      "artifact-remittance-comparison-aperture",
    ],
  },
  {
    id: "payment-intent-bluefield-9044",
    invoiceId: "invoice-bluefield-9044",
    vendorId: "vendor-bluefield-field-services",
    operatingEntity: "Helios Retail Group",
    amount: 22140,
    currency: "USD",
    paymentMethod: "ach",
    destinationBankAccountId: "bank-bluefield-primary",
    scheduledExecutionDate: "2026-04-05",
    status: "draft",
    approvalThresholdAmount: 30000,
    artifactIds: [
      "artifact-invoice-bluefield-9044-pdf",
      "artifact-site-completion-note-hel-118",
      "artifact-w9-bluefield-2026",
    ],
  },
  {
    id: "payment-intent-cinder-3308",
    invoiceId: "invoice-cinder-3308",
    vendorId: "vendor-cinder-cloud",
    operatingEntity: "Northwind Distribution",
    amount: 162480,
    currency: "USD",
    paymentMethod: "wire",
    destinationBankAccountId: "bank-cinder-primary",
    scheduledExecutionDate: "2026-04-04",
    status: "pending_review",
    approvalThresholdAmount: 150000,
    artifactIds: [
      "artifact-invoice-cinder-3308-pdf",
      "artifact-consumption-report-cinder-feb",
      "artifact-msa-cinder-cloud",
    ],
  },
] satisfies PaymentIntent[];

export const workerFixturesById = indexById(workerFixtures);
export const artifactFixturesById = indexById(artifactFixtures);
export const vendorFixturesById = indexById(vendorFixtures);
export const purchaseOrderFixturesById = indexById(purchaseOrderFixtures);
export const invoiceFixturesById = indexById(invoiceFixtures);
export const paymentIntentFixturesById = indexById(paymentIntentFixtures);

export const businessFixtureGroups = {
  workers: workerFixtures,
  artifacts: artifactFixtures,
  vendors: vendorFixtures,
  purchaseOrders: purchaseOrderFixtures,
  invoices: invoiceFixtures,
  paymentIntents: paymentIntentFixtures,
} as const;
