import type {
  ApprovalRequest,
  ControlReference,
  PlannedToolInvocation,
  PolicyRule,
  WorkflowScenario,
} from "../contracts";
import { seededWorkerRegistry, seededWorkers } from "./state";

function pickWorkers(...ids: string[]) {
  return ids.map((id) => seededWorkerRegistry[id]);
}

function tool(
  id: string,
  toolName: string,
  summary: string,
  executionMode: PlannedToolInvocation["executionMode"] = "shadow",
): PlannedToolInvocation {
  return { id, toolName, summary, executionMode };
}

function controlRef(
  kind: ControlReference["kind"],
  id: string,
  label: string,
  status: ControlReference["status"],
): ControlReference {
  return { kind, id, label, status };
}

function approvalControl(request: ApprovalRequest): ControlReference {
  return controlRef("approval", request.id, request.title, request.status === "pending" ? "pending" : "resolved");
}

const policyRules = {
  trustedVendor: {
    id: "POL-TRUSTED-VENDOR",
    name: "Trusted vendor match",
    description: "Trusted vendors with unchanged remittance details can remain in the low-risk path.",
    outcome: "allow",
    scope: "vendor_validation",
  } satisfies PolicyRule,
  amountVariance: {
    id: "POL-AMOUNT-VARIANCE",
    name: "Invoice to PO variance threshold",
    description: "Invoice totals above tolerance must hold before any posting or payment action proceeds.",
    outcome: "escalate",
    scope: "invoice_match",
  } satisfies PolicyRule,
  bankDrift: {
    id: "POL-BANK-DRIFT",
    name: "Vendor bank change hold",
    description: "Mid-cycle remittance changes remain blocked until separate evidence resolves the drift.",
    outcome: "block",
    scope: "vendor_validation",
  } satisfies PolicyRule,
  receivingEvidence: {
    id: "POL-RECEIVING-EVIDENCE",
    name: "Receiving evidence required",
    description: "Accrual exceptions cannot complete without receiving proof or a named override.",
    outcome: "block",
    scope: "exception_triage",
  } satisfies PolicyRule,
};

const northwindApproval: ApprovalRequest = {
  id: "APR-203",
  title: "Authorize Northwind payment release",
  actionLabel: "Release payment intent after mismatch review",
  status: "pending",
  requestedAt: "2026-03-30T09:41:00.000Z",
  assigneeLabel: "AP Controller · Priya Shah",
  reason: "Invoice total exceeds the matched PO by 7.8% and the worker stopped before ERP posting.",
};

export const seededScenarios: WorkflowScenario[] = [
  {
    id: "helios-monthly-media",
    runId: "FIN-4464",
    workflowKey: "invoice-reconciliation",
    workflowLabel: "Helios monthly media invoice",
    companyName: "Helios Retail Group",
    title: "Trusted invoice clears into controlled execution",
    narrative:
      "A low-risk invoice packet moves through review in shadow mode, then hands off to a controlled execution step once the evidence stack is complete.",
    seedTime: "2026-03-30T09:12:00.000Z",
    executionMode: "shadow",
    workers: pickWorkers(
      "intake-worker",
      "document-review-worker",
      "risk-worker",
      "execution-worker",
      "audit-narrator",
    ),
    riskAssessment: {
      id: "RSK-HELIOS-LOW",
      severity: "low",
      score: 18,
      summary: "Trusted vendor, matched PO, and no variance triggers surfaced during shadow review.",
      factors: ["vendor trust intact", "invoice amount matches PO", "payment window already scheduled"],
    },
    policyRules: [policyRules.trustedVendor],
    approvalRequests: [],
    approvalDecisions: [],
    artifacts: [
      {
        id: "ART-HELIOS-INV",
        kind: "invoice",
        title: "Invoice INV-10271",
        summary: "Inbound media services invoice captured from the AP inbox.",
        source: "email",
        status: "captured",
        createdAt: "2026-03-30T09:12:00.000Z",
        linkedEntityId: "INV-HELIOS-10271",
      },
      {
        id: "ART-HELIOS-PO",
        kind: "purchase_order",
        title: "PO PO-88214",
        summary: "Matched purchase order for the media services line items.",
        source: "erp",
        status: "reviewed",
        createdAt: "2026-03-30T09:15:00.000Z",
        linkedEntityId: "PO-HELIOS-88214",
      },
      {
        id: "ART-HELIOS-PAY",
        kind: "payment_intent",
        title: "Payment intent PAY-6614",
        summary: "Controlled posting package staged for supervised ERP execution.",
        source: "simulation",
        status: "produced",
        createdAt: "2026-03-30T09:25:00.000Z",
        linkedEntityId: "PAY-HELIOS-6614",
      },
      {
        id: "ART-HELIOS-RCPT",
        kind: "receipt",
        title: "Execution receipt draft",
        summary: "Replay-friendly receipt placeholder for the clean completion path.",
        source: "simulation",
        status: "derived",
        createdAt: "2026-03-30T09:29:00.000Z",
      },
    ],
    invoice: {
      id: "INV-HELIOS-10271",
      invoiceNumber: "INV-10271",
      vendorId: "VND-HELIOS-MEDIA",
      amountUsd: 24850,
      submittedAt: "2026-03-30T09:12:00.000Z",
      dueDate: "2026-04-07T00:00:00.000Z",
    },
    vendor: {
      id: "VND-HELIOS-MEDIA",
      name: "North Star Media Services",
      trustTier: "trusted",
      lastVerifiedAt: "2026-03-12T10:00:00.000Z",
    },
    purchaseOrder: {
      id: "PO-HELIOS-88214",
      poNumber: "PO-88214",
      amountUsd: 24850,
      issuedAt: "2026-03-15T00:00:00.000Z",
    },
    paymentIntent: {
      id: "PAY-HELIOS-6614",
      amountUsd: 24850,
      beneficiary: "North Star Media Services",
      method: "ach",
      scheduledFor: "2026-04-03T00:00:00.000Z",
    },
    stepTemplates: [
      {
        id: "STEP-HELIOS-INTAKE",
        key: "intake",
        title: "Capture invoice packet",
        description: "Ingest the inbound invoice and normalize the case metadata.",
        sequence: 1,
        assignedWorkerId: "intake-worker",
        executionMode: "shadow",
        dependsOnStepIds: [],
        artifactIds: ["ART-HELIOS-INV"],
        toolInvocations: [tool("TOOL-HELIOS-OCR", "invoice_ocr", "Extract invoice header and totals.")],
        controlRefs: [],
      },
      {
        id: "STEP-HELIOS-REVIEW",
        key: "document-review",
        title: "Review extracted fields",
        description: "Validate the invoice payload and attach matched purchasing evidence.",
        sequence: 2,
        assignedWorkerId: "document-review-worker",
        executionMode: "shadow",
        dependsOnStepIds: ["STEP-HELIOS-INTAKE"],
        artifactIds: ["ART-HELIOS-INV"],
        toolInvocations: [tool("TOOL-HELIOS-MATCH", "po_match", "Match extracted invoice details against the PO.")],
        controlRefs: [],
      },
      {
        id: "STEP-HELIOS-RISK",
        key: "risk-review",
        title: "Confirm low-risk posture",
        description: "Verify the run can leave shadow mode for the final controlled action.",
        sequence: 3,
        assignedWorkerId: "risk-worker",
        executionMode: "shadow",
        dependsOnStepIds: ["STEP-HELIOS-REVIEW"],
        artifactIds: ["ART-HELIOS-INV", "ART-HELIOS-PO"],
        toolInvocations: [tool("TOOL-HELIOS-RISK", "risk_summary", "Summarize variance and vendor posture.")],
        controlRefs: [],
      },
      {
        id: "STEP-HELIOS-EXECUTE",
        key: "controlled-execution",
        title: "Stage controlled ERP posting",
        description: "Move the prepared posting package through the supervised execute path.",
        sequence: 4,
        assignedWorkerId: "execution-worker",
        executionMode: "execute",
        dependsOnStepIds: ["STEP-HELIOS-RISK"],
        artifactIds: ["ART-HELIOS-PAY"],
        toolInvocations: [tool("TOOL-HELIOS-ERP", "erp_posting", "Stage the ERP posting package.", "execute")],
        controlRefs: [],
      },
    ],
    directives: [
      { kind: "run_status", atMinute: 1, toStatus: "planning", title: "Run moved into supervised planning", detail: "The seeded run was instantiated from a trusted vendor invoice scenario." },
      { kind: "run_status", atMinute: 2, toStatus: "in_progress", title: "Run entered active progression", detail: "The workflow advanced from planning into monitored execution." },
      { kind: "step_status", atMinute: 2, stepId: "STEP-HELIOS-INTAKE", toStatus: "ready", title: "Intake step is ready", detail: "Invoice capture is prepared for supervised processing." },
      { kind: "step_status", atMinute: 3, stepId: "STEP-HELIOS-INTAKE", toStatus: "in_progress", title: "Intake Worker started invoice capture", detail: "Inbound invoice artifacts are being normalized for the run." },
      { kind: "step_status", atMinute: 5, stepId: "STEP-HELIOS-INTAKE", toStatus: "completed", title: "Invoice packet normalized", detail: "The invoice header, totals, and vendor identifiers were extracted without exception.", outcomeSummary: "Invoice packet normalized for downstream review." },
      { kind: "handoff", atMinute: 6, stepId: "STEP-HELIOS-REVIEW", nextWorkerId: "document-review-worker", title: "Run handed to Document Review Worker", detail: "Structured invoice output moved into document review." },
      { kind: "step_status", atMinute: 6, stepId: "STEP-HELIOS-REVIEW", toStatus: "ready", title: "Document review queued", detail: "PO matching can begin with the normalized invoice payload." },
      { kind: "step_status", atMinute: 7, stepId: "STEP-HELIOS-REVIEW", toStatus: "in_progress", title: "Document Review Worker began PO matching", detail: "The worker is validating extracted fields against the purchase order." },
      { kind: "artifact", atMinute: 9, stepId: "STEP-HELIOS-REVIEW", artifactIds: ["ART-HELIOS-PO"], title: "Purchase order evidence attached", detail: "The matched purchase order was bundled into the review step." },
      { kind: "step_status", atMinute: 10, stepId: "STEP-HELIOS-REVIEW", toStatus: "completed", title: "Document review cleared", detail: "Invoice details and PO values aligned with no missing evidence.", outcomeSummary: "PO alignment confirmed for trusted vendor flow." },
      { kind: "handoff", atMinute: 11, stepId: "STEP-HELIOS-RISK", nextWorkerId: "risk-worker", title: "Run handed to Risk Worker", detail: "The case moved into a final low-risk posture check." },
      { kind: "step_status", atMinute: 11, stepId: "STEP-HELIOS-RISK", toStatus: "ready", title: "Risk review is ready", detail: "The worker has the matched evidence stack needed for the final shadow check." },
      { kind: "step_status", atMinute: 12, stepId: "STEP-HELIOS-RISK", toStatus: "in_progress", title: "Risk Worker evaluated the matched case", detail: "No tolerance triggers or vendor anomalies were found in the shadow pass." },
      { kind: "step_status", atMinute: 14, stepId: "STEP-HELIOS-RISK", toStatus: "completed", title: "Low-risk posture confirmed", detail: "The run is clear to leave shadow mode for the controlled execution step.", outcomeSummary: "Low-risk posture confirmed." },
      { kind: "mode", atMinute: 15, stepId: "STEP-HELIOS-EXECUTE", mode: "execute", title: "Run moved from shadow to execute", detail: "The final controlled action is now authorized to use the execute lane.", workerId: "execution-worker" },
      { kind: "handoff", atMinute: 15, stepId: "STEP-HELIOS-EXECUTE", nextWorkerId: "execution-worker", title: "Run handed to Execution Worker", detail: "The supervised posting package moved into the execute lane." },
      { kind: "step_status", atMinute: 15, stepId: "STEP-HELIOS-EXECUTE", toStatus: "ready", title: "Controlled execution staged", detail: "The ERP posting package is ready for the final supervised action." },
      { kind: "step_status", atMinute: 16, stepId: "STEP-HELIOS-EXECUTE", toStatus: "in_progress", title: "Execution Worker staged ERP posting", detail: "The controlled posting package is being issued to the live execution lane." },
      { kind: "artifact", atMinute: 17, stepId: "STEP-HELIOS-EXECUTE", artifactIds: ["ART-HELIOS-PAY", "ART-HELIOS-RCPT"], title: "Execution artifacts attached", detail: "The payment intent and receipt draft were linked to the live step." },
      { kind: "step_status", atMinute: 18, stepId: "STEP-HELIOS-EXECUTE", toStatus: "completed", title: "Controlled execution completed", detail: "The posting package completed inside the execute lane with a retained receipt draft.", outcomeSummary: "Controlled ERP posting completed." },
      { kind: "run_status", atMinute: 19, toStatus: "completed", title: "Run completed cleanly", detail: "The workflow closed with a full evidence trail and a controlled execution outcome." },
    ],
  },
  {
    id: "northwind-payment-hold",
    runId: "FIN-4471",
    workflowKey: "payment-release-review",
    workflowLabel: "Northwind invoice reconciliation",
    companyName: "Northwind Distribution",
    title: "Invoice mismatch pauses before payment release",
    narrative:
      "A three-way mismatch is surfaced in shadow mode, the risky action is packaged for a named reviewer, and the run remains in a visible waiting posture.",
    seedTime: "2026-03-30T09:19:00.000Z",
    executionMode: "shadow",
    workers: pickWorkers(
      "intake-worker",
      "document-review-worker",
      "risk-worker",
      "approval-coordinator",
      "audit-narrator",
    ),
    riskAssessment: {
      id: "RSK-NORTHWIND-HIGH",
      severity: "high",
      score: 86,
      summary: "Invoice total exceeds the matched PO threshold, so payment release must stay halted pending review.",
      factors: ["invoice exceeds PO by 7.8%", "payment release is high-stakes", "mismatch evidence was retained"],
    },
    policyRules: [policyRules.amountVariance],
    approvalRequests: [northwindApproval],
    approvalDecisions: [],
    artifacts: [
      {
        id: "ART-NORTHWIND-INV",
        kind: "invoice",
        title: "Invoice INV-88401",
        summary: "Inbound freight settlement invoice for Northwind Distribution.",
        source: "email",
        status: "captured",
        createdAt: "2026-03-30T09:19:00.000Z",
        linkedEntityId: "INV-NORTHWIND-88401",
      },
      {
        id: "ART-NORTHWIND-PO",
        kind: "purchase_order",
        title: "PO PO-50117",
        summary: "Matched PO for the scheduled freight services.",
        source: "erp",
        status: "reviewed",
        createdAt: "2026-03-30T09:23:00.000Z",
        linkedEntityId: "PO-NORTHWIND-50117",
      },
      {
        id: "ART-NORTHWIND-NOTE",
        kind: "exception_note",
        title: "Three-way mismatch receipt",
        summary: "Receipt documenting the amount variance that blocked payment release.",
        source: "simulation",
        status: "derived",
        createdAt: "2026-03-30T09:31:00.000Z",
      },
    ],
    invoice: {
      id: "INV-NORTHWIND-88401",
      invoiceNumber: "INV-88401",
      vendorId: "VND-NORTHWIND-FRT",
      amountUsd: 61840,
      submittedAt: "2026-03-30T09:19:00.000Z",
      dueDate: "2026-04-04T00:00:00.000Z",
    },
    vendor: {
      id: "VND-NORTHWIND-FRT",
      name: "Cascade Freight Partners",
      trustTier: "trusted",
      lastVerifiedAt: "2026-03-09T09:00:00.000Z",
    },
    purchaseOrder: {
      id: "PO-NORTHWIND-50117",
      poNumber: "PO-50117",
      amountUsd: 57380,
      issuedAt: "2026-03-18T00:00:00.000Z",
    },
    paymentIntent: {
      id: "PAY-NORTHWIND-203",
      amountUsd: 61840,
      beneficiary: "Cascade Freight Partners",
      method: "wire",
      scheduledFor: "2026-03-31T00:00:00.000Z",
    },
    exceptionCase: {
      id: "EXC-NORTHWIND-MISMATCH",
      code: "invoice_po_mismatch",
      summary: "Invoice amount exceeds PO tolerance and requires controller review.",
      severity: "high",
    },
    stepTemplates: [
      {
        id: "STEP-NORTHWIND-INTAKE",
        key: "intake",
        title: "Capture invoice packet",
        description: "Normalize the inbound invoice and prepare the workflow packet.",
        sequence: 1,
        assignedWorkerId: "intake-worker",
        executionMode: "shadow",
        dependsOnStepIds: [],
        artifactIds: ["ART-NORTHWIND-INV"],
        toolInvocations: [tool("TOOL-NORTHWIND-OCR", "invoice_ocr", "Extract the invoice totals and vendor identifiers.")],
        controlRefs: [],
      },
      {
        id: "STEP-NORTHWIND-REVIEW",
        key: "document-review",
        title: "Match invoice against PO",
        description: "Validate the invoice amount against the purchase order and receiving context.",
        sequence: 2,
        assignedWorkerId: "document-review-worker",
        executionMode: "shadow",
        dependsOnStepIds: ["STEP-NORTHWIND-INTAKE"],
        artifactIds: ["ART-NORTHWIND-INV"],
        toolInvocations: [tool("TOOL-NORTHWIND-MATCH", "po_match", "Compare invoice values against the PO amount.")],
        controlRefs: [],
      },
      {
        id: "STEP-NORTHWIND-RISK",
        key: "risk-review",
        title: "Assess mismatch severity",
        description: "Package the amount variance into a supervised control decision.",
        sequence: 3,
        assignedWorkerId: "risk-worker",
        executionMode: "shadow",
        dependsOnStepIds: ["STEP-NORTHWIND-REVIEW"],
        artifactIds: ["ART-NORTHWIND-INV", "ART-NORTHWIND-PO"],
        toolInvocations: [tool("TOOL-NORTHWIND-RISK", "variance_check", "Calculate PO variance and tolerance posture.")],
        controlRefs: [],
      },
      {
        id: "STEP-NORTHWIND-APPROVAL",
        key: "approval-coordination",
        title: "Hold payment release for controller review",
        description: "Open the approval gate and keep the risky action in a waiting state.",
        sequence: 4,
        assignedWorkerId: "approval-coordinator",
        executionMode: "shadow",
        dependsOnStepIds: ["STEP-NORTHWIND-RISK"],
        artifactIds: ["ART-NORTHWIND-NOTE"],
        toolInvocations: [tool("TOOL-NORTHWIND-BRIEF", "approval_brief", "Prepare the controller brief for the blocked payment release.")],
        controlRefs: [],
      },
    ],
    directives: [
      { kind: "run_status", atMinute: 1, toStatus: "planning", title: "Run moved into supervised planning", detail: "The payment release scenario was instantiated from a seeded mismatch case." },
      { kind: "run_status", atMinute: 2, toStatus: "in_progress", title: "Run entered active progression", detail: "Workers started advancing the invoice review in shadow mode." },
      { kind: "step_status", atMinute: 2, stepId: "STEP-NORTHWIND-INTAKE", toStatus: "ready", title: "Intake step is ready", detail: "The run is prepared for invoice normalization." },
      { kind: "step_status", atMinute: 3, stepId: "STEP-NORTHWIND-INTAKE", toStatus: "in_progress", title: "Intake Worker started invoice capture", detail: "Inbound invoice details are being normalized for supervised review." },
      { kind: "step_status", atMinute: 5, stepId: "STEP-NORTHWIND-INTAKE", toStatus: "completed", title: "Invoice packet normalized", detail: "Core invoice metadata is now available for PO matching.", outcomeSummary: "Invoice packet prepared for match review." },
      { kind: "handoff", atMinute: 6, stepId: "STEP-NORTHWIND-REVIEW", nextWorkerId: "document-review-worker", title: "Run handed to Document Review Worker", detail: "The invoice packet moved into PO matching." },
      { kind: "step_status", atMinute: 6, stepId: "STEP-NORTHWIND-REVIEW", toStatus: "ready", title: "PO match step queued", detail: "The matched purchase order is available for review." },
      { kind: "step_status", atMinute: 7, stepId: "STEP-NORTHWIND-REVIEW", toStatus: "in_progress", title: "Document Review Worker began PO matching", detail: "Invoice totals are being compared against the purchase order." },
      { kind: "artifact", atMinute: 9, stepId: "STEP-NORTHWIND-REVIEW", artifactIds: ["ART-NORTHWIND-PO"], title: "Purchase order evidence attached", detail: "The PO record was attached before the variance review step." },
      { kind: "step_status", atMinute: 10, stepId: "STEP-NORTHWIND-REVIEW", toStatus: "completed", title: "PO variance surfaced", detail: "The invoice total exceeded the PO threshold and the case moved into risk review.", outcomeSummary: "PO mismatch packaged for risk review." },
      { kind: "handoff", atMinute: 11, stepId: "STEP-NORTHWIND-RISK", nextWorkerId: "risk-worker", title: "Run handed to Risk Worker", detail: "The variance case moved into supervised risk analysis." },
      { kind: "step_status", atMinute: 11, stepId: "STEP-NORTHWIND-RISK", toStatus: "ready", title: "Risk review is ready", detail: "The mismatch evidence stack is ready for analysis." },
      { kind: "step_status", atMinute: 12, stepId: "STEP-NORTHWIND-RISK", toStatus: "in_progress", title: "Risk Worker evaluated the variance", detail: "The worker calculated the amount mismatch against the approved PO." },
      {
        kind: "artifact",
        atMinute: 13,
        stepId: "STEP-NORTHWIND-RISK",
        artifactIds: ["ART-NORTHWIND-NOTE"],
        title: "Mismatch receipt attached",
        detail: "A three-way mismatch receipt was attached before the payment release was halted.",
      },
      {
        kind: "step_status",
        atMinute: 14,
        stepId: "STEP-NORTHWIND-RISK",
        toStatus: "completed",
        title: "Risk Worker halted the release path",
        detail: "The worker refused execution and packaged the mismatch evidence for human review.",
        outcomeSummary: "Variance packaged into a supervised hold.",
        controlRefs: [controlRef("policy", "POL-AMOUNT-VARIANCE", "Invoice to PO variance threshold", "linked")],
      },
      { kind: "handoff", atMinute: 15, stepId: "STEP-NORTHWIND-APPROVAL", nextWorkerId: "approval-coordinator", title: "Run handed to Approval Coordinator", detail: "The risky release moved into the human gate lane." },
      {
        kind: "step_status",
        atMinute: 15,
        stepId: "STEP-NORTHWIND-APPROVAL",
        toStatus: "ready",
        title: "Approval brief staged",
        detail: "The controller review package is ready to open.",
        controlRefs: [approvalControl(northwindApproval)],
      },
      {
        kind: "step_status",
        atMinute: 16,
        stepId: "STEP-NORTHWIND-APPROVAL",
        toStatus: "waiting",
        title: "Approval Coordinator opened a human gate",
        detail: "Payment release remains paused until the named controller decides on the mismatch exception.",
        blockedReason: northwindApproval.reason,
        controlRefs: [approvalControl(northwindApproval)],
      },
      {
        kind: "run_status",
        atMinute: 16,
        toStatus: "waiting",
        title: "Run is waiting on controller review",
        detail: "The workflow is paused in a supervised waiting state rather than attempting execution.",
        controlRefs: [approvalControl(northwindApproval)],
      },
    ],
  },
  {
    id: "aperture-vendor-drift",
    runId: "FIN-4468",
    workflowKey: "vendor-bank-change-review",
    workflowLabel: "Aperture vendor onboarding check",
    companyName: "Aperture Logistics",
    title: "Vendor bank detail drift blocks progression",
    narrative:
      "A supplier changes remittance details mid-cycle, the review stays in shadow mode, and the run becomes blocked pending evidence that does not yet exist.",
    seedTime: "2026-03-30T09:08:00.000Z",
    executionMode: "shadow",
    workers: pickWorkers(
      "intake-worker",
      "vendor-review-worker",
      "risk-worker",
      "audit-narrator",
    ),
    riskAssessment: {
      id: "RSK-APERTURE-BLOCK",
      severity: "medium",
      score: 71,
      summary: "Vendor remittance details changed before the prior billing cycle settled, so the run remains blocked.",
      factors: ["bank details changed mid-cycle", "historic remittance profile no longer matches", "evidence remains incomplete"],
    },
    policyRules: [policyRules.bankDrift],
    approvalRequests: [],
    approvalDecisions: [],
    artifacts: [
      {
        id: "ART-APERTURE-INV",
        kind: "invoice",
        title: "Invoice INV-54022",
        summary: "Vendor invoice submitted alongside updated bank details.",
        source: "vendor_portal",
        status: "captured",
        createdAt: "2026-03-30T09:08:00.000Z",
        linkedEntityId: "INV-APERTURE-54022",
      },
      {
        id: "ART-APERTURE-VENDOR",
        kind: "vendor_profile",
        title: "Vendor remittance profile",
        summary: "Historic vendor profile showing a mid-cycle account change.",
        source: "erp",
        status: "reviewed",
        createdAt: "2026-03-30T09:13:00.000Z",
        linkedEntityId: "VND-APERTURE-932",
      },
      {
        id: "ART-APERTURE-NOTE",
        kind: "exception_note",
        title: "Bank drift exception note",
        summary: "Exception summary documenting unresolved remittance drift.",
        source: "simulation",
        status: "derived",
        createdAt: "2026-03-30T09:17:00.000Z",
      },
    ],
    invoice: {
      id: "INV-APERTURE-54022",
      invoiceNumber: "INV-54022",
      vendorId: "VND-APERTURE-932",
      amountUsd: 14220,
      submittedAt: "2026-03-30T09:08:00.000Z",
      dueDate: "2026-04-06T00:00:00.000Z",
    },
    vendor: {
      id: "VND-APERTURE-932",
      name: "Blue Mesa Freight Tech",
      trustTier: "monitored",
      lastVerifiedAt: "2026-02-28T00:00:00.000Z",
    },
    exceptionCase: {
      id: "EXC-APERTURE-BANK",
      code: "vendor_bank_drift",
      summary: "Supplier bank details changed inside the active payment cycle.",
      severity: "medium",
    },
    stepTemplates: [
      {
        id: "STEP-APERTURE-INTAKE",
        key: "intake",
        title: "Capture vendor submission",
        description: "Ingest the vendor packet and normalize the account-change request.",
        sequence: 1,
        assignedWorkerId: "intake-worker",
        executionMode: "shadow",
        dependsOnStepIds: [],
        artifactIds: ["ART-APERTURE-INV"],
        toolInvocations: [tool("TOOL-APERTURE-INTAKE", "vendor_packet_parse", "Normalize the inbound vendor update packet.")],
        controlRefs: [],
      },
      {
        id: "STEP-APERTURE-VENDOR",
        key: "vendor-review",
        title: "Cross-check vendor remittance profile",
        description: "Compare the updated bank details against the historic vendor profile.",
        sequence: 2,
        assignedWorkerId: "vendor-review-worker",
        executionMode: "shadow",
        dependsOnStepIds: ["STEP-APERTURE-INTAKE"],
        artifactIds: ["ART-APERTURE-INV"],
        toolInvocations: [tool("TOOL-APERTURE-BANK", "bank_profile_diff", "Compare new bank instructions with historic remittance data.")],
        controlRefs: [],
      },
      {
        id: "STEP-APERTURE-RISK",
        key: "risk-hold",
        title: "Hold remittance drift case",
        description: "Block the workflow until separate evidence resolves the bank-detail change.",
        sequence: 3,
        assignedWorkerId: "risk-worker",
        executionMode: "shadow",
        dependsOnStepIds: ["STEP-APERTURE-VENDOR"],
        artifactIds: ["ART-APERTURE-VENDOR", "ART-APERTURE-NOTE"],
        toolInvocations: [tool("TOOL-APERTURE-RISK", "remittance_hold", "Hold the run pending independent account verification.")],
        controlRefs: [],
      },
    ],
    directives: [
      { kind: "run_status", atMinute: 1, toStatus: "planning", title: "Run moved into supervised planning", detail: "The vendor change case was instantiated from a seeded remittance-drift scenario." },
      { kind: "run_status", atMinute: 2, toStatus: "in_progress", title: "Run entered active progression", detail: "The workflow advanced into monitored vendor review." },
      { kind: "step_status", atMinute: 2, stepId: "STEP-APERTURE-INTAKE", toStatus: "ready", title: "Vendor intake is ready", detail: "The inbound vendor packet is staged for normalization." },
      { kind: "step_status", atMinute: 3, stepId: "STEP-APERTURE-INTAKE", toStatus: "in_progress", title: "Intake Worker started vendor packet capture", detail: "The worker is normalizing the invoice and remittance update details." },
      { kind: "step_status", atMinute: 5, stepId: "STEP-APERTURE-INTAKE", toStatus: "completed", title: "Vendor packet normalized", detail: "The remittance change request is ready for cross-check.", outcomeSummary: "Vendor packet normalized for review." },
      { kind: "handoff", atMinute: 6, stepId: "STEP-APERTURE-VENDOR", nextWorkerId: "vendor-review-worker", title: "Run handed to Vendor Review Worker", detail: "The case moved into bank-detail comparison." },
      { kind: "step_status", atMinute: 6, stepId: "STEP-APERTURE-VENDOR", toStatus: "ready", title: "Vendor review queued", detail: "Historic remittance data is available for comparison." },
      { kind: "step_status", atMinute: 7, stepId: "STEP-APERTURE-VENDOR", toStatus: "in_progress", title: "Vendor Review Worker began cross-check", detail: "The worker is comparing updated bank details against prior remittance history." },
      { kind: "artifact", atMinute: 9, stepId: "STEP-APERTURE-VENDOR", artifactIds: ["ART-APERTURE-VENDOR"], title: "Historic vendor profile attached", detail: "The prior remittance profile was attached for side-by-side review." },
      { kind: "step_status", atMinute: 10, stepId: "STEP-APERTURE-VENDOR", toStatus: "completed", title: "Vendor drift packaged", detail: "The bank-detail change could not be cleared and was sent into a supervised hold.", outcomeSummary: "Vendor drift packaged for risk hold." },
      { kind: "handoff", atMinute: 11, stepId: "STEP-APERTURE-RISK", nextWorkerId: "risk-worker", title: "Run handed to Risk Worker", detail: "The unresolved remittance change moved into the control lane." },
      {
        kind: "step_status",
        atMinute: 11,
        stepId: "STEP-APERTURE-RISK",
        toStatus: "ready",
        title: "Risk hold is ready",
        detail: "The bank-drift evidence is ready to be evaluated for a hold decision.",
      },
      {
        kind: "step_status",
        atMinute: 12,
        stepId: "STEP-APERTURE-RISK",
        toStatus: "blocked",
        title: "Risk Worker blocked progression",
        detail: "The run cannot proceed until independent vendor verification clears the remittance drift.",
        blockedReason: "Independent verification for the new bank account has not been received.",
        controlRefs: [controlRef("policy", "POL-BANK-DRIFT", "Vendor bank change hold", "linked")],
      },
      {
        kind: "artifact",
        atMinute: 12,
        stepId: "STEP-APERTURE-RISK",
        artifactIds: ["ART-APERTURE-NOTE"],
        title: "Bank drift note attached",
        detail: "The unresolved remittance-drift note was attached to the blocked risk step.",
      },
      {
        kind: "run_status",
        atMinute: 12,
        toStatus: "blocked",
        title: "Run is blocked pending vendor verification",
        detail: "The workflow remains in shadow mode and cannot advance without new evidence.",
        controlRefs: [controlRef("policy", "POL-BANK-DRIFT", "Vendor bank change hold", "linked")],
      },
    ],
  },
  {
    id: "beacon-accrual-failure",
    runId: "OPS-1182",
    workflowKey: "freight-accrual-triage",
    workflowLabel: "Freight accrual exception triage",
    companyName: "Beacon Freight Services",
    title: "Missing receiving evidence ends in a failed exception path",
    narrative:
      "An accrual exception is routed through intake and review, but the run fails after the evidence needed to resolve the exception never arrives.",
    seedTime: "2026-03-30T08:57:00.000Z",
    executionMode: "shadow",
    workers: pickWorkers(
      "intake-worker",
      "document-review-worker",
      "risk-worker",
      "audit-narrator",
    ),
    riskAssessment: {
      id: "RSK-BEACON-FAIL",
      severity: "medium",
      score: 74,
      summary: "Receiving proof never arrived for the exception case, so the supervised run ended in failure instead of hidden fallback.",
      factors: ["receiving evidence missing", "tolerance override unavailable", "exception path timed out"],
    },
    policyRules: [policyRules.receivingEvidence],
    approvalRequests: [],
    approvalDecisions: [],
    artifacts: [
      {
        id: "ART-BEACON-INV",
        kind: "invoice",
        title: "Invoice INV-99014",
        summary: "Freight accrual invoice missing receiving confirmation.",
        source: "email",
        status: "captured",
        createdAt: "2026-03-30T08:57:00.000Z",
        linkedEntityId: "INV-BEACON-99014",
      },
      {
        id: "ART-BEACON-NOTE",
        kind: "exception_note",
        title: "Missing receiving evidence note",
        summary: "Exception narrative documenting the absent receiving proof.",
        source: "simulation",
        status: "derived",
        createdAt: "2026-03-30T09:07:00.000Z",
      },
    ],
    invoice: {
      id: "INV-BEACON-99014",
      invoiceNumber: "INV-99014",
      vendorId: "VND-BEACON-001",
      amountUsd: 18890,
      submittedAt: "2026-03-30T08:57:00.000Z",
      dueDate: "2026-04-10T00:00:00.000Z",
    },
    vendor: {
      id: "VND-BEACON-001",
      name: "Summit Terminal Services",
      trustTier: "trusted",
      lastVerifiedAt: "2026-03-05T00:00:00.000Z",
    },
    exceptionCase: {
      id: "EXC-BEACON-MISSING-RECEIPT",
      code: "missing_receiving_evidence",
      summary: "Receiving evidence was never attached to the accrual exception case.",
      severity: "medium",
    },
    stepTemplates: [
      {
        id: "STEP-BEACON-INTAKE",
        key: "intake",
        title: "Capture accrual exception packet",
        description: "Normalize the inbound exception case and invoice metadata.",
        sequence: 1,
        assignedWorkerId: "intake-worker",
        executionMode: "shadow",
        dependsOnStepIds: [],
        artifactIds: ["ART-BEACON-INV"],
        toolInvocations: [tool("TOOL-BEACON-OCR", "invoice_ocr", "Extract freight accrual invoice data.")],
        controlRefs: [],
      },
      {
        id: "STEP-BEACON-REVIEW",
        key: "document-review",
        title: "Review exception evidence",
        description: "Confirm whether receiving evidence exists for the accrual case.",
        sequence: 2,
        assignedWorkerId: "document-review-worker",
        executionMode: "shadow",
        dependsOnStepIds: ["STEP-BEACON-INTAKE"],
        artifactIds: ["ART-BEACON-INV"],
        toolInvocations: [tool("TOOL-BEACON-DOCS", "receiving_lookup", "Check for receiving proof linked to the invoice.")],
        controlRefs: [],
      },
      {
        id: "STEP-BEACON-RISK",
        key: "exception-resolution",
        title: "Resolve exception path",
        description: "Attempt to resolve the exception or fail the run if evidence never arrives.",
        sequence: 3,
        assignedWorkerId: "risk-worker",
        executionMode: "shadow",
        dependsOnStepIds: ["STEP-BEACON-REVIEW"],
        artifactIds: ["ART-BEACON-NOTE"],
        toolInvocations: [tool("TOOL-BEACON-RISK", "exception_resolution", "Decide whether the exception can continue.")],
        controlRefs: [],
      },
    ],
    directives: [
      { kind: "run_status", atMinute: 1, toStatus: "planning", title: "Run moved into supervised planning", detail: "The exception case was instantiated from a seeded freight accrual scenario." },
      { kind: "run_status", atMinute: 2, toStatus: "in_progress", title: "Run entered active progression", detail: "The workflow advanced into exception review in shadow mode." },
      { kind: "step_status", atMinute: 2, stepId: "STEP-BEACON-INTAKE", toStatus: "ready", title: "Intake step is ready", detail: "The accrual packet is staged for intake normalization." },
      { kind: "step_status", atMinute: 3, stepId: "STEP-BEACON-INTAKE", toStatus: "in_progress", title: "Intake Worker started exception intake", detail: "Invoice and exception metadata are being normalized." },
      { kind: "step_status", atMinute: 4, stepId: "STEP-BEACON-INTAKE", toStatus: "completed", title: "Exception packet normalized", detail: "The case is ready for evidence review.", outcomeSummary: "Exception packet prepared for evidence review." },
      { kind: "handoff", atMinute: 5, stepId: "STEP-BEACON-REVIEW", nextWorkerId: "document-review-worker", title: "Run handed to Document Review Worker", detail: "The case moved into receiving-evidence review." },
      { kind: "step_status", atMinute: 5, stepId: "STEP-BEACON-REVIEW", toStatus: "ready", title: "Evidence review queued", detail: "The workflow is ready to check for receiving proof." },
      { kind: "step_status", atMinute: 6, stepId: "STEP-BEACON-REVIEW", toStatus: "in_progress", title: "Document Review Worker searched for receiving proof", detail: "The worker checked linked documents for receipt confirmation." },
      { kind: "step_status", atMinute: 8, stepId: "STEP-BEACON-REVIEW", toStatus: "waiting", title: "Evidence review is waiting", detail: "The expected receiving proof did not arrive with the case.", blockedReason: "Receiving proof has not been attached." },
      { kind: "artifact", atMinute: 10, stepId: "STEP-BEACON-RISK", artifactIds: ["ART-BEACON-NOTE"], title: "Missing evidence note attached", detail: "A failure note was attached when the evidence timeout expired." },
      { kind: "handoff", atMinute: 10, stepId: "STEP-BEACON-RISK", nextWorkerId: "risk-worker", title: "Run handed to Risk Worker", detail: "The unresolved exception moved into a final control decision." },
      { kind: "step_status", atMinute: 10, stepId: "STEP-BEACON-RISK", toStatus: "ready", title: "Exception resolution is ready", detail: "The final control step is staged with the missing-evidence note attached." },
      { kind: "step_status", atMinute: 10, stepId: "STEP-BEACON-RISK", toStatus: "in_progress", title: "Risk Worker attempted exception resolution", detail: "The worker evaluated whether the run could continue without receiving proof." },
      {
        kind: "step_status",
        atMinute: 11,
        stepId: "STEP-BEACON-RISK",
        toStatus: "failed",
        title: "Risk Worker failed the exception path",
        detail: "The run could not proceed because required receiving evidence never arrived.",
        blockedReason: "Required receiving evidence never arrived before timeout.",
        controlRefs: [controlRef("policy", "POL-RECEIVING-EVIDENCE", "Receiving evidence required", "linked")],
      },
      {
        kind: "run_status",
        atMinute: 11,
        toStatus: "failed",
        title: "Run failed under supervision",
        detail: "The workflow ended explicitly instead of silently bypassing the missing-evidence control.",
        controlRefs: [controlRef("policy", "POL-RECEIVING-EVIDENCE", "Receiving evidence required", "linked")],
      },
    ],
  },
];

export const seededScenarioRegistry = Object.fromEntries(
  seededScenarios.map((scenario) => [scenario.id, scenario]),
) as Record<string, WorkflowScenario>;

export const allSeededWorkers = seededWorkers;
