import type { SeededAegisData } from "./contracts";

export const seededAegisData: SeededAegisData = {
  workers: [
    {
      id: "worker-intake",
      name: "Intake Worker",
      role: "Document intake and case assembly",
      focus: "Normalizing inbound invoice packets and opening supervised workflow runs.",
      posture: "Stable",
      queueDepth: 4,
      loadPercent: 72,
    },
    {
      id: "worker-vendor-review",
      name: "Vendor Review Worker",
      role: "Vendor identity and remittance verification",
      focus: "Cross-checking remittance changes before any payment release can resume.",
      posture: "Watching",
      queueDepth: 2,
      loadPercent: 64,
    },
    {
      id: "worker-risk",
      name: "Risk Worker",
      role: "Exception scoring and evidence capture",
      focus: "Building explainable mismatch packets for human review and downstream replay.",
      posture: "Escalated",
      queueDepth: 3,
      loadPercent: 88,
    },
    {
      id: "worker-approval",
      name: "Approval Coordinator",
      role: "Human gate routing and control handoff",
      focus: "Holding risky actions in named approval queues with clear resume paths.",
      posture: "Coordinating",
      queueDepth: 3,
      loadPercent: 57,
    },
    {
      id: "worker-execution",
      name: "Execution Worker",
      role: "Controlled ERP posting preparation",
      focus: "Preparing execute-ready payment packets once policy and approval gates clear.",
      posture: "Ready",
      queueDepth: 1,
      loadPercent: 39,
    },
  ],
  scenarios: [
    {
      id: "scenario-northwind-mismatch",
      title: "Three-way mismatch hold",
      phase: "Seeded scenario",
      narrative:
        "A payment release moved smoothly until invoice and PO totals diverged. The worker paused, surfaced evidence, and routed a controller approval before ERP execution.",
      watchpoints: [
        "Mismatch evidence is visible before any manual approval is taken.",
        "The risky step is contained without making the rest of the workflow disappear.",
        "A reviewer can see exactly what resumes next after sign-off.",
      ],
      run: {
        id: "FIN-4471",
        workflow: "Northwind invoice reconciliation",
        accountName: "Northwind Distribution",
        status: "waiting_for_approval",
        mode: "shadow",
        riskLevel: "high",
        currentStage: "Awaiting controller sign-off on payment release",
        ownerWorkerId: "worker-approval",
        nextAction: "Escalate payment release with mismatch evidence bundle",
        etaMinutes: 6,
      },
      vendor: {
        id: "vendor-northwind",
        name: "Northwind Distribution",
        trustTier: "trusted",
        region: "US East",
      },
      invoice: {
        id: "invoice-northwind-mar",
        invoiceNumber: "NW-20418",
        amountUsd: 182400,
        currency: "USD",
        receivedAt: "2026-03-30T09:12:00Z",
      },
      purchaseOrder: {
        id: "po-northwind-mar",
        poNumber: "PO-88211",
        amountUsd: 169200,
        status: "variance",
      },
      paymentIntent: {
        id: "payment-northwind-mar",
        amountUsd: 182400,
        beneficiary: "Northwind Distribution",
        scheduledDate: "2026-03-31",
        status: "paused",
      },
      artifacts: [
        {
          id: "artifact-northwind-invoice",
          kind: "invoice",
          title: "Invoice packet NW-20418",
          summary: "Invoice, line-item extraction, and normalized remittance profile.",
        },
        {
          id: "artifact-northwind-po",
          kind: "purchase_order",
          title: "Purchase order PO-88211",
          summary: "Matched PO baseline showing a 7.8% amount variance versus invoice total.",
        },
        {
          id: "artifact-northwind-receipt",
          kind: "mismatch_receipt",
          title: "Three-way mismatch receipt",
          summary: "Worker-generated evidence packet with totals, tolerance, and variance notes.",
        },
      ],
      steps: [
        {
          id: "step-northwind-intake",
          runId: "FIN-4471",
          title: "Invoice packet normalized",
          summary: "Inbound documents were parsed and attached to the run record.",
          status: "completed",
          workerId: "worker-intake",
          mode: "shadow",
        },
        {
          id: "step-northwind-po-match",
          runId: "FIN-4471",
          title: "PO variance detected",
          summary: "Invoice total exceeded the approved purchase order tolerance.",
          status: "completed",
          workerId: "worker-risk",
          mode: "shadow",
        },
        {
          id: "step-northwind-approval",
          runId: "FIN-4471",
          title: "Controller approval requested",
          summary: "Payment release is paused until the AP controller approves or rejects the exception.",
          status: "waiting_for_approval",
          workerId: "worker-approval",
          mode: "shadow",
        },
        {
          id: "step-northwind-release",
          runId: "FIN-4471",
          title: "ERP payment release",
          summary: "Controlled execution window remains locked until approval resumes the run.",
          status: "blocked",
          workerId: "worker-execution",
          mode: "execute_ready",
        },
      ],
      policies: [
        {
          id: "policy-payment-variance",
          name: "Payment variance above PO tolerance",
          scope: "Payment release",
          summary: "Escalate when invoice total exceeds approved PO tolerance before posting.",
          trigger: "Invoice total is 7.8% above matched PO amount.",
          outcome: "escalate",
          severity: "high",
        },
        {
          id: "policy-erp-execution-gate",
          name: "Execute-ready release requires cleared approval",
          scope: "ERP posting",
          summary: "Block ERP release until the approval request resolves.",
          trigger: "Pending human gate exists on a payment-sensitive action.",
          outcome: "block",
          severity: "high",
        },
      ],
      approvals: [
        {
          id: "APR-203",
          runId: "FIN-4471",
          title: "Authorize Northwind payment release",
          requestedAction: "Resume ERP posting for the March payment packet.",
          reason: "Invoice total exceeds PO by 7.8% and the worker paused before release.",
          assignee: "AP Controller · Priya Shah",
          dueLabel: "Due in 18 min",
          status: "pending",
          riskLevel: "high",
          triggerLabel: "Mismatch hold",
        },
      ],
      events: [
        {
          id: "event-northwind-1",
          runId: "FIN-4471",
          timestamp: "2026-03-30T09:18:00Z",
          title: "Intake Worker normalized invoice packet",
          detail: "Invoice packet NW-20418 was converted into a supervised workflow record.",
          actorName: "Intake Worker",
          category: "Intake",
          riskLevel: "low",
        },
        {
          id: "event-northwind-2",
          runId: "FIN-4471",
          timestamp: "2026-03-30T09:31:00Z",
          title: "Risk Worker captured variance evidence",
          detail: "PO tolerance breach was bundled into a replay-friendly mismatch receipt.",
          actorName: "Risk Worker",
          category: "Evidence",
          riskLevel: "high",
        },
        {
          id: "event-northwind-3",
          runId: "FIN-4471",
          timestamp: "2026-03-30T09:41:00Z",
          title: "Approval Coordinator paused payment release",
          detail: "ERP execution was held open only as a future controlled step after controller review.",
          actorName: "Approval Coordinator",
          category: "Escalation",
          riskLevel: "high",
        },
      ],
    },
    {
      id: "scenario-aperture-bank-drift",
      title: "Vendor remittance drift review",
      phase: "Seeded scenario",
      narrative:
        "A trusted supplier requested a bank detail change inside the same billing cycle. The worker stayed in shadow mode and opened a focused review instead of auto-updating remittance data.",
      watchpoints: [
        "Remittance changes are treated separately from invoice matching.",
        "Vendor history is visible before any account update resumes.",
        "The control surface stays specific about who must review the drift.",
      ],
      run: {
        id: "FIN-4468",
        workflow: "Aperture vendor onboarding check",
        accountName: "Aperture Logistics",
        status: "waiting_for_approval",
        mode: "shadow",
        riskLevel: "medium",
        currentStage: "Vendor bank detail revision under cross-check",
        ownerWorkerId: "worker-vendor-review",
        nextAction: "Confirm account update against historic remittance profile",
        etaMinutes: 11,
      },
      vendor: {
        id: "vendor-aperture",
        name: "Aperture Logistics",
        trustTier: "watch",
        region: "US Central",
      },
      invoice: {
        id: "invoice-aperture-mar",
        invoiceNumber: "AP-88103",
        amountUsd: 124600,
        currency: "USD",
        receivedAt: "2026-03-30T08:54:00Z",
      },
      paymentIntent: {
        id: "payment-aperture-mar",
        amountUsd: 124600,
        beneficiary: "Aperture Logistics",
        scheduledDate: "2026-04-02",
        status: "prepared",
      },
      artifacts: [
        {
          id: "artifact-aperture-invoice",
          kind: "invoice",
          title: "Invoice packet AP-88103",
          summary: "Inbound invoice plus remittance change request submitted in the same packet.",
        },
        {
          id: "artifact-aperture-bank-change",
          kind: "bank_change_request",
          title: "Bank detail change request",
          summary: "Supplier-submitted account update pending historical remittance verification.",
        },
      ],
      steps: [
        {
          id: "step-aperture-intake",
          runId: "FIN-4468",
          title: "Vendor packet assembled",
          summary: "Invoice and bank-change documents were grouped into one supervised case.",
          status: "completed",
          workerId: "worker-intake",
          mode: "shadow",
        },
        {
          id: "step-aperture-remittance-check",
          runId: "FIN-4468",
          title: "Historic remittance cross-check",
          summary: "The worker compared the requested account against prior settled payments.",
          status: "running",
          workerId: "worker-vendor-review",
          mode: "shadow",
        },
        {
          id: "step-aperture-approval",
          runId: "FIN-4468",
          title: "Bank-detail approval hold",
          summary: "Supplier account swap requires named risk review before any payment release can proceed.",
          status: "waiting_for_approval",
          workerId: "worker-approval",
          mode: "shadow",
        },
      ],
      policies: [
        {
          id: "policy-bank-drift",
          name: "Vendor bank-detail change requires review",
          scope: "Vendor remittance",
          summary: "Escalate supplier account changes requested inside the active billing cycle.",
          trigger: "Bank account changed before the previous invoice batch fully settled.",
          outcome: "escalate",
          severity: "medium",
        },
      ],
      approvals: [
        {
          id: "APR-204",
          runId: "FIN-4468",
          title: "Approve vendor bank-detail change",
          requestedAction: "Allow the updated remittance profile to replace the prior account.",
          reason: "Supplier requested an account swap inside the same billing cycle.",
          assignee: "Vendor Risk Lead · Marcus Hale",
          dueLabel: "Due in 42 min",
          status: "pending",
          riskLevel: "medium",
          triggerLabel: "Account drift",
        },
      ],
      events: [
        {
          id: "event-aperture-1",
          runId: "FIN-4468",
          timestamp: "2026-03-30T09:04:00Z",
          title: "Intake Worker opened vendor review case",
          detail: "Bank change request was attached before any payment-sensitive action advanced.",
          actorName: "Intake Worker",
          category: "Intake",
          riskLevel: "low",
        },
        {
          id: "event-aperture-2",
          runId: "FIN-4468",
          timestamp: "2026-03-30T09:36:00Z",
          title: "Risk Worker attached vendor drift evidence",
          detail: "Historical remittance patterns were bundled before the approval request opened.",
          actorName: "Risk Worker",
          category: "Evidence",
          riskLevel: "medium",
        },
      ],
    },
    {
      id: "scenario-helios-clean-posting",
      title: "Clean invoice ready for controlled posting",
      phase: "Seeded scenario",
      narrative:
        "A trusted vendor invoice cleared PO matching and is staged as execute-ready. The route demonstrates that low-risk work keeps moving without losing visible controls.",
      watchpoints: [
        "Low-risk work still shows worker ownership and execution posture.",
        "Execute-ready does not mean uncontrolled execution.",
        "The same run structure supports both smooth and risky paths.",
      ],
      run: {
        id: "FIN-4464",
        workflow: "Helios monthly media invoice",
        accountName: "Helios Retail Group",
        status: "running",
        mode: "execute_ready",
        riskLevel: "low",
        currentStage: "PO match cleared and posting draft prepared",
        ownerWorkerId: "worker-execution",
        nextAction: "Open controlled ERP posting window for review",
        etaMinutes: 3,
      },
      vendor: {
        id: "vendor-helios",
        name: "Helios Retail Group",
        trustTier: "trusted",
        region: "US West",
      },
      invoice: {
        id: "invoice-helios-mar",
        invoiceNumber: "HE-30091",
        amountUsd: 64200,
        currency: "USD",
        receivedAt: "2026-03-30T09:02:00Z",
      },
      purchaseOrder: {
        id: "po-helios-mar",
        poNumber: "PO-90144",
        amountUsd: 64200,
        status: "matched",
      },
      paymentIntent: {
        id: "payment-helios-mar",
        amountUsd: 64200,
        beneficiary: "Helios Retail Group",
        scheduledDate: "2026-03-30",
        status: "ready",
      },
      artifacts: [
        {
          id: "artifact-helios-payment",
          kind: "payment_packet",
          title: "ERP posting packet",
          summary: "Posting draft prepared with matched invoice, PO, and payment instructions.",
        },
      ],
      steps: [
        {
          id: "step-helios-intake",
          runId: "FIN-4464",
          title: "Invoice packet normalized",
          summary: "Inbound packet was structured into a standard payment workflow.",
          status: "completed",
          workerId: "worker-intake",
          mode: "shadow",
        },
        {
          id: "step-helios-po-match",
          runId: "FIN-4464",
          title: "PO match cleared",
          summary: "Invoice amount and PO baseline aligned with no tolerance issues.",
          status: "completed",
          workerId: "worker-risk",
          mode: "shadow",
        },
        {
          id: "step-helios-posting",
          runId: "FIN-4464",
          title: "ERP posting draft staged",
          summary: "Execution packet is prepared for the controlled posting window.",
          status: "running",
          workerId: "worker-execution",
          mode: "execute_ready",
        },
      ],
      policies: [
        {
          id: "policy-clean-match",
          name: "Matched invoice can proceed in supervised execution",
          scope: "Invoice posting",
          summary: "Allow matched invoices to move from shadow processing into execute-ready preparation.",
          trigger: "Invoice, PO, and vendor profile aligned with no exception signals.",
          outcome: "allow",
          severity: "low",
        },
      ],
      approvals: [],
      events: [
        {
          id: "event-helios-1",
          runId: "FIN-4464",
          timestamp: "2026-03-30T09:28:00Z",
          title: "Execution Worker cleared Helios posting draft",
          detail: "PO match and invoice metadata aligned, so the run moved into execute-ready state.",
          actorName: "Execution Worker",
          category: "Advance",
          riskLevel: "low",
        },
      ],
    },
    {
      id: "scenario-beacon-accrual-exception",
      title: "Freight accrual evidence gap",
      phase: "Seeded scenario",
      narrative:
        "A freight accrual run encountered incomplete receiving evidence. The worker kept the exception visible and asked operations finance to approve a tolerance override.",
      watchpoints: [
        "Evidence gaps trigger a focused exception path instead of silent failure.",
        "The affected worker and human owner remain obvious.",
        "Operational context stays close to the blocked action.",
      ],
      run: {
        id: "OPS-1182",
        workflow: "Freight accrual exception triage",
        accountName: "Beacon Freight Services",
        status: "blocked",
        mode: "shadow",
        riskLevel: "medium",
        currentStage: "Mismatch analysis waiting on receiving evidence",
        ownerWorkerId: "worker-risk",
        nextAction: "Request dock receipt artifact before variance recommendation",
        etaMinutes: 14,
      },
      vendor: {
        id: "vendor-beacon",
        name: "Beacon Freight Services",
        trustTier: "watch",
        region: "US Southeast",
      },
      invoice: {
        id: "invoice-beacon-mar",
        invoiceNumber: "BF-07712",
        amountUsd: 111300,
        currency: "USD",
        receivedAt: "2026-03-30T08:41:00Z",
      },
      purchaseOrder: {
        id: "po-beacon-mar",
        poNumber: "PO-11890",
        amountUsd: 109700,
        status: "missing_receipt",
      },
      paymentIntent: {
        id: "payment-beacon-mar",
        amountUsd: 111300,
        beneficiary: "Beacon Freight Services",
        scheduledDate: "2026-04-01",
        status: "paused",
      },
      artifacts: [
        {
          id: "artifact-beacon-dock",
          kind: "dock_receipt",
          title: "Receiving receipt placeholder",
          summary: "Receiving evidence is still missing from the exception packet.",
        },
      ],
      steps: [
        {
          id: "step-beacon-intake",
          runId: "OPS-1182",
          title: "Freight invoice classified",
          summary: "Accrual packet was categorized and routed into exception triage.",
          status: "completed",
          workerId: "worker-intake",
          mode: "shadow",
        },
        {
          id: "step-beacon-evidence",
          runId: "OPS-1182",
          title: "Receiving evidence requested",
          summary: "Run is blocked until receiving proof or a manual tolerance override arrives.",
          status: "blocked",
          workerId: "worker-risk",
          mode: "shadow",
        },
        {
          id: "step-beacon-override",
          runId: "OPS-1182",
          title: "Tolerance override approval",
          summary: "Operations finance can approve the exception if evidence remains unavailable.",
          status: "waiting_for_approval",
          workerId: "worker-approval",
          mode: "shadow",
        },
      ],
      policies: [
        {
          id: "policy-missing-evidence",
          name: "Missing receiving proof blocks closeout",
          scope: "Freight accrual closeout",
          summary: "Block closeout when receiving evidence is missing from the invoice packet.",
          trigger: "Dock receipt was not attached to the matched accrual case.",
          outcome: "block",
          severity: "medium",
        },
      ],
      approvals: [
        {
          id: "APR-205",
          runId: "OPS-1182",
          title: "Release freight accrual exception path",
          requestedAction: "Approve a manual tolerance override for closeout.",
          reason: "Receiving evidence is incomplete, so the run is holding for manual tolerance approval.",
          assignee: "Operations Finance · Elena Ruiz",
          dueLabel: "Due in 55 min",
          status: "pending",
          riskLevel: "medium",
          triggerLabel: "Tolerance override",
        },
      ],
      events: [
        {
          id: "event-beacon-1",
          runId: "OPS-1182",
          timestamp: "2026-03-30T09:22:00Z",
          title: "Intake Worker routed freight accrual exception",
          detail: "Missing receiving proof triggered a handoff into the risk lane instead of automatic posting.",
          actorName: "Intake Worker",
          category: "Handoff",
          riskLevel: "medium",
        },
      ],
    },
    {
      id: "scenario-atlas-safe-match",
      title: "Trusted supplier auto-match",
      phase: "Seeded scenario",
      narrative:
        "A low-risk office supply invoice completed the supervised shadow path with no approval requirements, showing the calmer side of the same operating model.",
      watchpoints: [
        "Completed runs still retain audit traces and worker attribution.",
        "Low-risk work should not vanish from the product narrative.",
        "Safe scenarios provide a useful contrast to exceptions.",
      ],
      run: {
        id: "FIN-4459",
        workflow: "Atlas office supply invoice",
        accountName: "Atlas Workplace",
        status: "completed",
        mode: "shadow",
        riskLevel: "low",
        currentStage: "Receipt generated for replay handoff",
        ownerWorkerId: "worker-execution",
        nextAction: "Archive receipt and keep replay frame available",
        etaMinutes: 0,
      },
      vendor: {
        id: "vendor-atlas",
        name: "Atlas Workplace",
        trustTier: "trusted",
        region: "US Midwest",
      },
      invoice: {
        id: "invoice-atlas-mar",
        invoiceNumber: "AT-55014",
        amountUsd: 17800,
        currency: "USD",
        receivedAt: "2026-03-30T07:48:00Z",
      },
      purchaseOrder: {
        id: "po-atlas-mar",
        poNumber: "PO-55014",
        amountUsd: 17800,
        status: "matched",
      },
      paymentIntent: {
        id: "payment-atlas-mar",
        amountUsd: 17800,
        beneficiary: "Atlas Workplace",
        scheduledDate: "2026-03-30",
        status: "released",
      },
      artifacts: [
        {
          id: "artifact-atlas-receipt",
          kind: "payment_packet",
          title: "Execution receipt",
          summary: "Safe-path receipt retained for replay and audit views.",
        },
      ],
      steps: [
        {
          id: "step-atlas-intake",
          runId: "FIN-4459",
          title: "Invoice intake completed",
          summary: "Inbound packet was parsed with no document gaps.",
          status: "completed",
          workerId: "worker-intake",
          mode: "shadow",
        },
        {
          id: "step-atlas-match",
          runId: "FIN-4459",
          title: "Vendor and PO matched",
          summary: "Trusted supplier invoice aligned with purchasing records.",
          status: "completed",
          workerId: "worker-risk",
          mode: "shadow",
        },
        {
          id: "step-atlas-close",
          runId: "FIN-4459",
          title: "Receipt recorded",
          summary: "Run closed with a replay-ready receipt artifact.",
          status: "completed",
          workerId: "worker-execution",
          mode: "shadow",
        },
      ],
      policies: [
        {
          id: "policy-trusted-auto-match",
          name: "Trusted supplier auto-match remains supervised",
          scope: "Standard invoice closeout",
          summary: "Allow trusted, fully matched supplier invoices to close without extra review.",
          trigger: "Vendor trust tier remained high and all financial records matched.",
          outcome: "allow",
          severity: "low",
        },
      ],
      approvals: [],
      events: [
        {
          id: "event-atlas-1",
          runId: "FIN-4459",
          timestamp: "2026-03-30T08:26:00Z",
          title: "Execution Worker archived safe-path receipt",
          detail: "Completed run moved into replay-ready state with no outstanding approvals.",
          actorName: "Execution Worker",
          category: "Complete",
          riskLevel: "low",
        },
      ],
    },
  ],
};
